SHELL=/bin/bash

CC = nvcc -g -O
NVCC = nvcc -G -g -O3


# EBI uses the following with pgcc, -O3 does not work:
# CC= pgcc -O2 -pipe -mcpu=pentiumpro -march=pentiumpro -fomit-frame-pointer

# this file works for x86 LINUX

# standard options

.SUFFIXES:
.SUFFIXES:  .cpp .c .cxx .cu .o .h

CFLAGS= -DSHOW_HELP -DSHOWSIM -DUNIX -DTIMES -DHZ=100 -DMAX_WORKERS=8 -DUSE_MMAP -DTHR_EXI$
# -I/usr/include/mysql -DMYSQL_DB
# -DSUPERFAMNUM -DSFCHAR="'|'" 

#
#(for mySQL databases)  (also requires change to Makefile36m.common or use of M$
# run 'mysql_config' so find locations of mySQL files

LIB_M = -lm -lcuda -lcudart -lcublas -lcufft -lstdc++ -lpthread
# for mySQL databases
# LIB_M = -L/usr/lib64/mysql -lmysqlclient -lm

HFLAGS= -o
NFLAGS= -o

# for Linux
THR_SUBS = pthr_subs2
THR_LIBS = -lpthread
THR_CC =

BIN = ../bin
XDIR = /seqprg/bin
#XDIR = ~/bin/LINUX

# set up files for SSE2/Altivec/GPU acceleration
#
include ../make/Makefile.sse_alt

# SSE2 acceleration
#
DROPGSW_O = $(DROPGSW_NA_O)
DROPLAL_O = $(DROPLAL_NA_O)
DROPGNW_O = $(DROPGNW_NA_O)
DROPLNW_O = $(DROPLNW_NA_O)

# renamed (fasta36)  programs
include ../make/Makefile36m.common
# conventional (fasta3) names
# include ../make/Makefile.common
